export const SubscribeError = Object.freeze({
	MISSING_FIELDS: "MISSING_FIELDS",
	INVALID_EMAIL: "INVALID_EMAIL",
	INVALID_REPO_FORMAT: "INVALID_REPO_FORMAT",
	REPO_NOT_FOUND: "REPO_NOT_FOUND",
	RATE_LIMITED: "RATE_LIMITED",
	ALREADY_EXISTS: "ALREADY_EXISTS",
	INTERNAL: "INTERNAL",
});
